export const APP_CONSTANTS = {
  WEBSOCKET: {
    RECONNECTION_DELAY_MS: 1000,
    RECONNECTION_ATTEMPTS: 5,
  },

  PAGINATION: {
    NOTIFICATIONS_DEFAULT_LIMIT: 50,
    TASK_HISTORY_ITEMS_PER_PAGE: 10,
  },

  CACHE: {
    USERS_STALE_TIME_MS: 5 * 60 * 1000,
    QUERY_STALE_TIME_MS: 1000 * 60 * 5,
    QUERY_GC_TIME_MS: 1000 * 60 * 10,
    QUERY_RETRY_COUNT: 1,
  },

  VALIDATION: {
    USERNAME_MIN_LENGTH: 3,
    USERNAME_MAX_LENGTH: 50,
    TASK_DESCRIPTION_MAX_LENGTH: 1000,
  },

  TIME: {
    SECONDS_IN_MINUTE: 60,
    MINUTES_IN_HOUR: 60,
    HOURS_IN_DAY: 24,
    MS_IN_SECOND: 1000,
  },
} as const;

